import { Inter } from "next/font/google";
import './globals.css'; // Ensure global styles are imported here
import ReduxProviderWrapper from './MyApp'; // Import the ReduxProvider component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                {/* Preconnect for Google Fonts */}
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                
                {/* Include custom fonts */}
                <link href="https://fonts.googleapis.com/css2?family=Playwrite+GB+S:ital,wght@0,100..400;1,100..400&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Trade+Winds&display=swap" rel="stylesheet" />
            </head>
            <body className={inter.className}>
                <ReduxProviderWrapper> {/* Use ReduxProviderWrapper here */}
                    {children}
                </ReduxProviderWrapper>
            </body>
        </html>
    );
}
